### ISSUE TITLE
How to start for the samd21

### ISSUE THREAD

**Issue by DonQuiShot** [wa1tnr/conversations#1]
Hi wa1tnr,

I am interested in a Forth for the Adafruit M0 Trinket, which is based on a samd21. I am new to all this, willing to learn and wondering if you could give me a pointer on where to start, given that you seem to have done already so much ground work.

Kind regards,

**Comment by wa1tnr** [comment]
Hi DonQuiShot.

I never seem to get notified of Issues here, so that's why the long delay.

YAFFA-ARM was the Forth I started with for any SAMD21 (I have a few Trinket M0's on-hand, here).

The unported version is full-fledged; the work I did with it never made it to a complete Forth vocabulary.  It works, but is limited in scope.  That's the ainsuForth-gen-exp-m4 series; despite the name I think it still runs on Trinket M0.  Haven't looked in a while.

I'm currently working with C.H. Ting's eForth for the STM32F407 Discovery board, which runs unaltered on the new STM32F405 Express (from Adafruit).

By far and away, the best Forth I've seen that runs on an Arduino-compatible board made by Adafruit.

As soon as you limit yourself to Trinket M0 you're back to Arduino based Forths, or (for the most part) unfinished designs/experiments.

I enjoyed all of them, but looking back on them, none got all that far along in coparison to the very complete eForth I'm now enjoying.

Still, if I need a quick Arduino IDE compiled Forth on any of my Adafruit SAMD21 or SAMD51 boards, I first reach for ainsuForth-gen-exp-m4 (which is a YAFFA-ARM port and update, and does support SPI flashROM on the Adafruit 'Express' boards that have SPI flashROM -- YAFFA-ARM never supported any external mass storage).

CamelForth is great; I ported it (into Atmel Start, I think) but I don't think it was ported into the Arduino IDE (not by me, anyway).

It's a very good Forth to study.  So is gforth (in Linux, for example) (also on the Android handheld platform!)

I have to recommend the STM32F405 Express (Adafruit) or STM32F407 Discovery (digikey sells this for $20 USD) and eForth.  That's where I'm putting my efforts these days.
